#' Loads commit stats (as generated by cloc) into a data frame, along with the commit ref and timestamp.
#' @export
#' @return data.frame of all commit line count stats
#' @examples
#' commit_stats <- load_commit_stats()
#' summary(commit_stats)
load_commit_stats <- function() {

  commits <- read.csv('out/commits.csv', header=FALSE, col.names=c('ref','timestamp'))

  adply(
    .data=commits,
    .margins=1,
    .fun=function(c) {
      f <- sprintf('./out/%s.csv', c$ref)
      if(file.exists(f)) {
        d <- read.csv(f)
        d <- d[grep("http", names(d), value=TRUE, invert=TRUE)] # Exclude "trash" columns
        d$ref <- c$ref
        d$timestamp <- as.POSIXct(c$timestamp)
        d
      }
    }
  )

}

#' Plots the lines f code for each language at each commit time.
#' @export
#' @param commit_stats
#' @return ggplot object
plot_commit_lines_of_code <- function(commit_stats) {
  ggplot(commit_stats, aes(x = timestamp, y = code, colour = language)) +
    geom_area(aes(fill = language), position = 'stack') 
}

