#' Loads commit stats (as generated by cloc) into a data frame, along with the commit ref and timestamp.
#' @export
#' @return data.frame of all commit line count stats
#' @examples
#' commit_stats <- load_commit_stats()
#' summary(commit_stats)
load_commit_stats <- function() {
  library(plyr)

  commits <- read.csv('out/commits.csv', header=FALSE, col.names=c('ref','timestamp'))

  adply(
    .data=commits,
    .margins=1,
    .fun=function(c) {
      f <- sprintf('./out/%s.csv', c$ref)
      if(file.exists(f)) {
        d <- read.csv(f)
        d <- d[grep("http", names(d), value=TRUE, invert=TRUE)] # Exclude "trash" columns
        d$ref <- c$ref
        d$timestamp <- as.POSIXct(c$timestamp)
        d
      }
    }
  )

}

#' Plots the lines f code for each language at each commit time.
#' @export
#' @param commit_stats
#' @param variable the variable to plot
#' @return ggplot object
plot_commit_stats<- function(commit_stats, variable) {
  library(ggplot2)
  ggplot(commit_stats, aes_string(x = 'timestamp', y = variable, colour = 'language')) +
    geom_area(aes(fill = language), position = 'stack') 
}


#' Plot all to PNG.
#' @export
#' @param commit_stats
plot_all_to_PNG <- function(commit_stats) {
  plot_to_png <- function(variable) {
    png(sprintf('./commit_%s.png', variable))
    print(plot_commit_stats(commit_stats, variable))
    dev.off()
  }
  plot_to_png('code')
  plot_to_png('files')
}
